### ISSUE TITLE
libcublas.so.*[0-9] not found in the system path

### ISSUE THREAD

**Issue by heluvaguy** [datagusto/datagusto#1]
Getting following error after docker compose up.

<pre>
1.373 Traceback (most recent call last):
1.373   File "/usr/local/lib/python3.9/site-packages/torch/__init__.py", line 176, in _load_global_deps
1.373     ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
1.373   File "/usr/local/lib/python3.9/ctypes/__init__.py", line 374, in __init__
1.373     self._handle = _dlopen(self._name, mode)
1.373 OSError: libcudart.so.12: cannot open shared object file: No such file or directory
1.373
1.373 During handling of the above exception, another exception occurred:
1.373
1.373 Traceback (most recent call last):
1.373   File "<string>", line 1, in <module>
1.373   File "/usr/src/app/custom_embedding.py", line 5, in <module>
1.373     from sentence_transformers import SentenceTransformer
1.373   File "/usr/local/lib/python3.9/site-packages/sentence_transformers/__init__.py", line 3, in <module>
1.373     from .datasets import SentencesDataset, ParallelSentencesDataset
1.373   File "/usr/local/lib/python3.9/site-packages/sentence_transformers/datasets/__init__.py", line 1, in <module>
1.373     from .DenoisingAutoEncoderDataset import DenoisingAutoEncoderDataset
1.373   File "/usr/local/lib/python3.9/site-packages/sentence_transformers/datasets/DenoisingAutoEncoderDataset.py", line 1, in <module>
1.373     from torch.utils.data import Dataset
1.373   File "/usr/local/lib/python3.9/site-packages/torch/__init__.py", line 236, in <module>
1.373     _load_global_deps()
1.373   File "/usr/local/lib/python3.9/site-packages/torch/__init__.py", line 197, in _load_global_deps
1.374     _preload_cuda_deps(lib_folder, lib_name)
1.374   File "/usr/local/lib/python3.9/site-packages/torch/__init__.py", line 162, in _preload_cuda_deps
1.374     raise ValueError(f"{lib_name} not found in the system path {sys.path}")
1.374 ValueError: libcublas.so.*[0-9] not found in the system path ['', '/usr/local/lib/python39.zip', '/usr/local/lib/python3.9', '/usr/local/lib/python3.9/lib-dynload', '/usr/local/lib/python3.9/site-packages']
</pre>

Please suggest what steps should be taken ?

**Comment by nkmrtty** [comment]
@heluvaguy 
Thank you for reporting the issue.
We will investigate your issues and get back to you soon!
I would be appreciate if you provide the information about your environment, such as OS, Docker version, what you tried before, etc.

**Comment by heluvaguy** [comment]
OS: Ubuntu 22.04.4 LTS
Docker Version: Docker version 26.1.1, build 4cf5afa


Steps done:

1.  Git checkout
2.  Create .env in backend as per the instructions
3.  Create .env in frontend folder as per the instructions
4.  execute command `docker compose up -d`

Is there a requirement of "cudnn" on the server before starting the containers ?

**Comment by huchka** [comment]
Thanks you for sharing your information. @heluvaguy 
Right now, we are working on the issue. We are planning to fix this issue by tomorrow (Friday, May 10th).

**Comment by huchka** [comment]
fixed on this PR
https://github.com/datagusto/datagusto/pull/2
